### ISSUE TITLE
Parse error while running tests

### ISSUE THREAD

**Issue by andigena** [bkiers/python3-parser#6]
Upon running `mvn clean install`, I've  encountered the following error (full output at https://gist.github.com/andigena/02f1491356505e30eda5):

```
parsing 102/721: 'register.py' ... java.lang.RuntimeException: source: null, line: 60, index: 13, error message: no viable alternative at input 'warn("' null
    at nl.bigo.pythonparser.DescriptiveBailErrorListener.syntaxError(DescriptiveBailErrorListener.java:22)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:67)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:561)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:147)
    at nl.bigo.pythonparser.Python3Parser.testlist_star_expr(Python3Parser.java:1820)
    at nl.bigo.pythonparser.Python3Parser.expr_stmt(Python3Parser.java:1598)
    at nl.bigo.pythonparser.Python3Parser.small_stmt(Python3Parser.java:1488)
    at nl.bigo.pythonparser.Python3Parser.simple_stmt(Python3Parser.java:1375)
    at nl.bigo.pythonparser.Python3Parser.stmt(Python3Parser.java:1309)
    at nl.bigo.pythonparser.Python3Parser.suite(Python3Parser.java:3722)
    at nl.bigo.pythonparser.Python3Parser.funcdef(Python3Parser.java:639)
    at nl.bigo.pythonparser.Python3Parser.compound_stmt(Python3Parser.java:3081)
    at nl.bigo.pythonparser.Python3Parser.stmt(Python3Parser.java:1322)
    at nl.bigo.pythonparser.Python3Parser.suite(Python3Parser.java:3722)
    at nl.bigo.pythonparser.Python3Parser.classdef(Python3Parser.java:6000)
    at nl.bigo.pythonparser.Python3Parser.compound_stmt(Python3Parser.java:3087)
    at nl.bigo.pythonparser.Python3Parser.stmt(Python3Parser.java:1322)
    at nl.bigo.pythonparser.Python3Parser.file_input(Python3Parser.java:310)
    at nl.bigo.pythonparser.Python3ParserTest.testParser(Python3ParserTest.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.499 sec <<< FAILURE!
testParser(nl.bigo.pythonparser.Python3ParserTest)  Time elapsed: 11.466 sec  <<< FAILURE!
java.lang.AssertionError: failed to parse d:\temp\antlr\python3-parser\src\test\python\cpython-3f944f44ee41\Lib\distutils\command\register.py
```

This is on Windows 7 x64, exact command line was `d:\temp\apache-maven-3.3.3\bin\mvn clean install`

**Comment by bkiers** [comment]
Hi, you are absolutely sure no changes have been made to either the test files, nor the grammar? When making a clean clone of this repository, both on Linux and Mac OS all tests succeed. I do not have access to a Windows machine, so if this is truly an OS specific thing, someone else will have to fix it.

**Comment by andigena** [comment]
Hi. Yes, it was an unmodified repo that failed. Logs of a clean try: https://gist.github.com/andigena/12d18eeb2201e1d3f937
This is with maven 3.3.3 and JDK 1.8
```
λ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
λ javac -version
javac 1.8.0_51
```
I've also tried on an Xubuntu 14.04 vm with maven 3.0.5 and 3.3.3 and OpenJDK 7, it went without problems.
